{

	Copyright 1990-2015, Jerome Shidel.

	This project and related files are subject to the terms of the Mozilla Public License, 
v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at 
http://mozilla.org/MPL/2.0/.

}

   uses QCrt, TxtMouse, PGM_UNIT, PGM_DLOG, Clock, Graph, Dos;

   procedure Stub;
      begin
         Sound (500);
         Delay (500);
         NoSound;
      end;
{$I PGM-DISK.PAS}
{$I PGM-SETP.PAS}
{$I PGM-SPEC.PAS}
{$I PGM-MENU.PAS}
{$I PGM-SCRN.PAS}
{$I PGM-WND1.PAS}
{$I PGM-HELP.PAS}
{$I PGM-SRCH.PAS}
{$I PGM-DSCP.PAS}
{$I PGM-WND2.PAS}
{$I PGM-EDIT.PAS}
{$I PGM-EXEC.PAS}
{$I PGM-NORM.PAS}
